const englishString = {
  "delicious_cooking": "Delicious cooking",
  "cooking_is_easy": "Cooking is easy",
  "login": "Login",
  "register": "Register",
  "email": "Email",
  "password": "Password",
  "re_password": "Re-enter password",
  "name": "Name",
  "forgot_pass": "Forgot password?",
  "do_not_have_account": "Don't have an account yet?",
  "do_you_forgot_pass": "Forgot your password?",
  "input_email": "Enter email",
  "input_otp": "Enter the OTP code sent to you",
  "next": "Continue",
  "do_you_have_account": "Already have an account?",
  "value_require": "@value can't be empty",
  "email_not_correct_format": "Email is not in correct format",
  "re_password_not_correct": "Re-enter password does not match",
  "input_your_email": "Enter your email",
  "verify_account": "Verify your email",
  "verify_account_success": "Verify your account success",
  "enter_new_pass": "Enter new password",
  "error_verify_pass": "Re_enter incorrect password",
  "enter_new_pass_to_login": "Please, enter new password to login",

  //home
  "search_recipe": "Search recipes",
  "mots_favorite": "Most favorites",

  //food detail
  "ingredient": "Ingredients",
  "instruction": "Instruction",
  "rating": "Review",
  "rating_lable_dialog": "Please rate the dish",
  "making": "Making",
  "cancel": "Cancel",
};
