const viString = {
  "delicious_cooking": "Nấu ăn ngon",
  "cooking_is_easy": "Nấu ăn là dễ",
  "login": "Đăng nhập",
  "register": "Đăng ký",
  "email": "Địa chỉ email",
  "password": "Mật khẩu",
  "re_password": "Nhập lại mật khẩu",
  "name": "Họ và tên",
  "forgot_pass": "Quên mật khẩu?",
  "do_not_have_account": "Bạn chưa có tài khoản?",
  "do_you_forgot_pass": "Bạn quên mật khẩu?",
  "input_email": "Nhập địa chỉ email",
  "input_otp": "Nhập mã OTP đã được gửi đến bạn",
  "next": "Tiếp tục",
  "do_you_have_account": "Bạn đã có tài khoản?",
  "value_require": "@value không được để trống",
  "email_not_correct_format": "Email không đúng định dạng",
  "re_password_not_correct": "Nhập lại mật khẩu không khớp",
  "input_your_email": "Nhập email của bạn",
  "verify_account": "Xác minh tài khoản của bạn",
  "verify_account_success": "Xác minh tài khoản thành công",
  "enter_new_pass": "Nhập mật khẩu mới",
  "error_verify_pass": "Nhập lại mật khẩu không đúng",
  "enter_new_pass_to_login": "Vui lòng nhập mật khẩu mới để đăng nhập",
};
