name: tutorial
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  fluttertoast: ^8.2.8
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  package_info_plus: ^8.0.2
  google_sign_in: ^6.2.1
  gap: ^3.0.1
  flutter_rating_bar: ^4.0.1
  auto_size_text: ^3.0.0
  flutter_advanced_drawer: ^1.3.6
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  collection: ^1.18.0
  searchfield: 1.2.0
  syncfusion_flutter_sliders: ^28.1.33
  syncfusion_flutter_charts: ^28.1.33
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/res/image/svg/
    - lib/res/image/png/
    - lib/res/image/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/res/font/Inter_ExtraBold.ttf
          weight: 800
        - asset: lib/res/font/Inter_Bold.ttf
          weight: 700
        - asset: lib/res/font/Inter_SemiBold.ttf
          weight: 600
        - asset: lib/res/font/Inter_Medium.ttf
          weight: 500
        - asset: lib/res/font/Inter_Regular.ttf
          weight: 400
    - family: Lora
      fonts:
        - asset: lib/res/font/Lora_Bold.ttf
          weight: 700
        - asset: lib/res/font/Lora_SemiBold.ttf
          weight: 600
        - asset: lib/res/font/Lora_Medium.ttf
          weight: 500
        - asset: lib/res/font/Lora_Regular.ttf
          weight: 400